services:
  - type: web
    name: customer-orders-app
    env: node
    plan: free
    buildCommand: "cd frontend && npm install --include=dev && npm run build && cd ../backend && npm install --include=dev && npm run build"
    startCommand: "cd backend && npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 22

  - type: web
    name: customer-orders-web
    env: static
    buildCommand: "cd frontend && npm install --include=dev && npm run build"
    staticPublishPath: "./frontend/dist/frontend/browser"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
